In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv("Churn_Modelling.csv")
data

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [3]:
X = data.iloc[:,3:13].values
Y = data.iloc[:,13].values

# Encoding categorical columns

In [4]:
pd.DataFrame(X)

        0        1       2   3   4          5  6  7  8          9
0     619   France  Female  42   2        0.0  1  1  1  101348.88
1     608    Spain  Female  41   1   83807.86  1  0  1  112542.58
2     502   France  Female  42   8   159660.8  3  1  0  113931.57
3     699   France  Female  39   1        0.0  2  0  0   93826.63
4     850    Spain  Female  43   2  125510.82  1  1  1    79084.1
...   ...      ...     ...  ..  ..        ... .. .. ..        ...
9995  771   France    Male  39   5        0.0  2  1  0   96270.64
9996  516   France    Male  35  10   57369.61  1  1  1  101699.77
9997  709   France  Female  36   7        0.0  1  0  1   42085.58
9998  772  Germany    Male  42   3   75075.31  2  1  0   92888.52
9999  792   France  Female  28   4  130142.79  1  1  0   38190.78

[10000 rows x 10 columns]

In [5]:
from sklearn import preprocessing

In [6]:
le = preprocessing.LabelEncoder()

In [7]:
X[:,1] = le.fit_transform(X[:,1])
X[:,2] = le.fit_transform(X[:,2])

In [8]:
pd.DataFrame(X)

        0  1  2   3   4          5  6  7  8          9
0     619  0  0  42   2        0.0  1  1  1  101348.88
1     608  2  0  41   1   83807.86  1  0  1  112542.58
2     502  0  0  42   8   159660.8  3  1  0  113931.57
3     699  0  0  39   1        0.0  2  0  0   93826.63
4     850  2  0  43   2  125510.82  1  1  1    79084.1
...   ... .. ..  ..  ..        ... .. .. ..        ...
9995  771  0  1  39   5        0.0  2  1  0   96270.64
9996  516  0  1  35  10   57369.61  1  1  1  101699.77
9997  709  0  0  36   7        0.0  1  0  1   42085.58
9998  772  1  1  42   3   75075.31  2  1  0   92888.52
9999  792  0  0  28   4  130142.79  1  1  0   38190.78

[10000 rows x 10 columns]

In [9]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ohe = ColumnTransformer([("ohe", OneHotEncoder(dtype=float),[1])],remainder="passthrough"
                        )
X = ohe.fit_transform(X)
X = X[:,1:]

# Split datas to train and test

In [11]:
from sklearn.model_selection import train_test_split

x_train, x_test,y_train,y_test = train_test_split(X,Y,test_size=0.33, random_state=0)

from sklearn.preprocessing import StandardScaler

sc=StandardScaler()

X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

# Create artificial neural network

In [12]:
from keras.models import Sequential
from keras.layers import Dense

2024-02-26 20:10:17.435539: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [13]:
classifier = Sequential()

classifier.add(Dense(6, activation = 'relu' , input_dim = 11))
classifier.add(Dense(6, activation = 'relu'))
classifier.add(Dense(6, activation = 'relu'))
classifier.add(Dense(1, activation = 'sigmoid'))

classifier.compile(optimizer = 'adam', loss =  'binary_crossentropy' , metrics = ['accuracy'] )

classifier.fit(X_train, y_train, epochs=100)

Epoch 1/100
210/210 [==============================] - 2s 2ms/step - loss: 0.5111 - accuracy: 0.7979
Epoch 2/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4634 - accuracy: 0.7979
Epoch 3/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4399 - accuracy: 0.7979
Epoch 4/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4238 - accuracy: 0.8106
Epoch 5/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4132 - accuracy: 0.8212
Epoch 6/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4069 - accuracy: 0.8231
Epoch 7/100
210/210 [==============================] - 0s 2ms/step - loss: 0.4030 - accuracy: 0.8231
Epoch 8/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3995 - accuracy: 0.8269
Epoch 9/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3961 - accuracy: 0.8288
Epoch 10/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3931 - accuracy: 0.8322
Epoch 11/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3906 - accuracy: 0.8321
Epoch 12/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3880 - accuracy: 0.8337
Epoch 13/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3860 - accuracy: 0.8321
Epoch 14/100
210/210 [==============================] - 1s 2ms/step - loss: 0.3840 - accuracy: 0.8345
Epoch 15/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3824 - accuracy: 0.8324
Epoch 16/100
210/210 [==============================] - 1s 2ms/step - loss: 0.3809 - accuracy: 0.8339
Epoch 17/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3788 - accuracy: 0.8352
Epoch 18/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3773 - accuracy: 0.8354
Epoch 19/100
210/210 [==============================] - 1s 2ms/step - loss: 0.3758 - accuracy: 0.8357
Epoch 20/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3738 - accuracy: 0.8357
Epoch 21/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3724 - accuracy: 0.8428
Epoch 22/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3703 - accuracy: 0.8461
Epoch 23/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3687 - accuracy: 0.8487
Epoch 24/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3670 - accuracy: 0.8499
Epoch 25/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3656 - accuracy: 0.8496
Epoch 26/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3634 - accuracy: 0.8539
Epoch 27/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3612 - accuracy: 0.8545
Epoch 28/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3599 - accuracy: 0.8560
Epoch 29/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3571 - accuracy: 0.8548
Epoch 30/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3549 - accuracy: 0.8569
Epoch 31/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3527 - accuracy: 0.8601
Epoch 32/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3505 - accuracy: 0.8588
Epoch 33/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3483 - accuracy: 0.8616
Epoch 34/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3463 - accuracy: 0.8601
Epoch 35/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3457 - accuracy: 0.8606
Epoch 36/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3442 - accuracy: 0.8616
Epoch 37/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3428 - accuracy: 0.8607
Epoch 38/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3412 - accuracy: 0.8622
Epoch 39/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3410 - accuracy: 0.8619
Epoch 40/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3394 - accuracy: 0.8612
Epoch 41/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3390 - accuracy: 0.8631
Epoch 42/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3379 - accuracy: 0.8636
Epoch 43/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3372 - accuracy: 0.8630
Epoch 44/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3368 - accuracy: 0.8619
Epoch 45/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3359 - accuracy: 0.8613
Epoch 46/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3360 - accuracy: 0.8619
Epoch 47/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3352 - accuracy: 0.8636
Epoch 48/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3357 - accuracy: 0.8628
Epoch 49/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3351 - accuracy: 0.8622
Epoch 50/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3342 - accuracy: 0.8631
Epoch 51/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3357 - accuracy: 0.8610
Epoch 52/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8633
Epoch 53/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3341 - accuracy: 0.8645
Epoch 54/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3346 - accuracy: 0.8622
Epoch 55/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3343 - accuracy: 0.8628
Epoch 56/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8627
Epoch 57/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3334 - accuracy: 0.8628
Epoch 58/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8628
Epoch 59/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3340 - accuracy: 0.8624
Epoch 60/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3345 - accuracy: 0.8637
Epoch 61/100
210/210 [==============================] - 1s 3ms/step - loss: 0.3339 - accuracy: 0.8627
Epoch 62/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8642
Epoch 63/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.8624
Epoch 64/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3334 - accuracy: 0.8604
Epoch 65/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3328 - accuracy: 0.8651
Epoch 66/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3326 - accuracy: 0.8643
Epoch 67/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3334 - accuracy: 0.8631
Epoch 68/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3333 - accuracy: 0.8652
Epoch 69/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8634
Epoch 70/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3339 - accuracy: 0.8637
Epoch 71/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3325 - accuracy: 0.8652
Epoch 72/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3330 - accuracy: 0.8619
Epoch 73/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3326 - accuracy: 0.8649
Epoch 74/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3324 - accuracy: 0.8627
Epoch 75/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3326 - accuracy: 0.8643
Epoch 76/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3319 - accuracy: 0.8645
Epoch 77/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3331 - accuracy: 0.8637
Epoch 78/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3321 - accuracy: 0.8625
Epoch 79/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3325 - accuracy: 0.8649
Epoch 80/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3326 - accuracy: 0.8657
Epoch 81/100

210/210 [==============================] - 0s 2ms/step - loss: 0.3329 - accuracy: 0.8634
Epoch 82/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3321 - accuracy: 0.8649
Epoch 83/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.8669
Epoch 84/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3316 - accuracy: 0.8649
Epoch 85/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3321 - accuracy: 0.8624
Epoch 86/100
210/210 [==============================] - 1s 2ms/step - loss: 0.3308 - accuracy: 0.8633
Epoch 87/100
210/210 [==============================] - 1s 2ms/step - loss: 0.3317 - accuracy: 0.8657
Epoch 88/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3319 - accuracy: 0.8643
Epoch 89/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3319 - accuracy: 0.8667
Epoch 90/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3315 - accuracy: 0.8637
Epoch 91/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3311 - accuracy: 0.8637
Epoch 92/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3319 - accuracy: 0.8645
Epoch 93/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3307 - accuracy: 0.8645
Epoch 94/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3314 - accuracy: 0.8654
Epoch 95/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3310 - accuracy: 0.8660
Epoch 96/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3309 - accuracy: 0.8657
Epoch 97/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3311 - accuracy: 0.8642
Epoch 98/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3314 - accuracy: 0.8669
Epoch 99/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3304 - accuracy: 0.8651
Epoch 100/100
210/210 [==============================] - 0s 2ms/step - loss: 0.3313 - accuracy: 0.8630

In [14]:
y_pred = classifier.predict(X_test)

y_pred = (y_pred > 0.5)

104/104 [==============================] - 0s 2ms/step

In [15]:
from sklearn.metrics import confusion_matrix

In [16]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[2507,  110],
       [ 370,  313]])